storyblok/storyblok-js-client

- source/index.js
if `query.cv` is provided do not use own caching strategy.
> allows CV param override

- dist/index.js
- source/index.js
The object-hash package was not used anymore but it was still required
in the source file. This lead to webpack failing with the following
message:
> This dependency was not found:
>
> * object-hash in ./node_modules/storyblok-js-client/dist/index.js
> Remove unused object-hash dependency

- dist/index.d.ts
The important thing that this PR should fix is that `Stories.data.stories` expected a single object rather than an array of objects. I have abstracted that object out into `StoryData` and allowed `Stories` to have an array of those:
```typescript
export interface StoryData {
alternates: string[]
content: {
component: string
_uid: string
[index: string]: any
}
created_at: string
full_slug: string
group_id: string
id: number
is_startpage: boolean
meta_data: any
name: string
parent_id: number
position: number
published_at: string | null
slug: string
sort_by_date: string | null
tag_list: string[]
uuid: string
}
export interface Stories {
data: {
stories: StoryData[]
}
perPage: number
total: number
headers: any
}
export interface Story {
data: {
story: StoryData
}
headers: any
}
```
Does this …
> BUGFIX: Stories should allow more than one story

- package.json
Storyblok-js client depends on axios version ^0.17.1. Current version shipped with nuxt is 0.18. 
I do have both axios 0.17.1 and 0.18 bundled by webpack. To avoid this duplicate content, it would be great to update package.json to now have 0.18.
I've made the very small change in the package.json. My npm install will change the package-lock.json so I didn't commit it. There are some vulnerabilities listed from npm install.
> upgraded axios to 0.18.0

- dist/index.d.ts
This change gives you the ability to pass a type for content in order to strongly type the `content` property
Example: 
```
interface MyContent {
heading: string
date: string
}
const story: StoryData<MyContent> = { ... }  
// This works
story.content.heading
// This will error
story.content.foobar
```
This wont affect the any current usages of the type
```
const story: StoryData = { ... }  
story.content.anythingYouWant
```
> Add ability to specify Content type for StoryData

- README.md
- dist/index.d.ts
- source/index.js
Currently it's not possible to use a cache provider that has async methods. This change allows you to do just that. Still works with built in `memory` provider
- Enable ability for CacheProvider to be `async`
- Restructured the call to the cache in `cachedResponse` if `params.version` isn't `published` as the response wasn't used.
- Added missing properties on `StoryblokConfig` interface
```
class Client extends Storyblok { 
cacheProvider() {
return {
get: async (key) =>  .... ,
set: async (key, content) =>  .... ,
flush: async () => ...
}
}
}
```
> Feat/Async Cache provider

- dist/index.d.ts
The current version creates 2 issues (at least in TS strict mode, version 3.5.3):
> Fix signature of getAll

- dist/index.d.ts
- package.json
This PR fixes:
* missing some type definitions in `StoriesParams` interface
* missing type definition of addComments function (reported by #41)
* missing `prepare` npm script to build the package before publish it
> missing type definitions and prepare npm script

- dist/index.d.ts
Currently `by_uuids_ordered` is  missing in the StoriesParams type. https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/retrieve-multiple-stories
> update StoriesParams with by_uuids_ordered

- README.md
- dist/index.d.ts
- source/richTextResolver.js
- tests/richTextResolver.test.js
Update the type definition and documentation about the `render` method in `RichtextInstance`.
> type definition to richtext render method

- dist/index.d.ts
According to the docs, the `alternates` property of a story is an object, not a string.
Source: https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/the-story-object
> Fix type of alternates property in `StoryData`

- source/richTextResolver.js
- tests/richTextResolver.test.js
[Relates to Storyblok Nuxt issue](https://github.com/storyblok/storyblok-nuxt/issues/8).
Use of `Array.slice` method before `Array.reverse` method to prevent Array mutation. This behavior can be a problem when the `Richtext.render` method receives as an argument a data that cannot change (like from Vuex, for example). And this PR makes the render method more "functional".
> richtext prevent content mutation

- source/richTextResolver.js
- tests/richTextResolver.test.js
This PR is a fix to #56. It's possible to escape characters without the semicolon, but, this can cause unexpected behaviors, like described in the referenced issue.
> Missing semicolon in htmlEscapes

- source/index.js
I have this error in my console on some rare occasions, make sure that node exists
> fix: make sure fieldtype exists on node

- source/index.js
Use management API version v1 if oauthToken is not set. Only set v2 of content delivery if `oauthToken` is not set. 
Currently Users will receive a 404 when using the JS client for management options.
Initialize the JS client with:
```
endpoint: "https://api.storyblok.com/v1"
```
> fix(client): use v1 for management API based on oauthToken

- source/index.js
This PR resolves #103 : it makes links and relations inside components and links in a Rich Text Editor field get the data from their linked stories. [These lines](https://github.com/storyblok/storyblok-js-client/blob/4a6ab2cd30089c6d863f3c610f1b75be5cdf2674/source/index.js#L182-L185) will inject the object also inside inline links.
> feat: story objects in links and relations inside the rich text editor

- source/index.js
This PR fixes an issue with the `resolveRelations` internal method not using the language parameter. If a user will perform a request for a specific language, the method was always returning the relations in the default language.
With this fix, the function will use the `language` parameter if set, otherwise it will use the `default` value for the language.
You can run the following code and check if the language set in the language parameter is the same you get in the resolved relations. 
```
import StoryblokClient from 'storyblok-js-client'
let client = new StoryblokClient({
accessToken: '' // You can take the preview token from the "CZ - JS Client Rel Fix" space
});
client.get('cdn/stories', {
version: 'draft',
resolve_relations: '',
starts_with: 'cities/paris/venues/sanctum', …
```
> fix: relations resolved with correct language

- types/index.d.ts
Add the missing `lang` and `translated_slugs` properties to the StoryData type
> fix(types): add `lang` and `translated_slugs` to StoryData

- types/index.d.ts
Add the missing `level` parameter to the types for retrieving multiple stories
> fix(types): add `level` to StoriesParams

- source/index.js
This PR fixes an issue with the links resolver method which is not passing the lang parameter along with the other parameters, so the resolved links are not in the same language as the retrieved stories. 
I've also removed the `default` fallback to the relations resolver as it would include also this bug #134 which is about languages too.
> fix: send the language parameter to links resolver

- package.json
- rollup.config.js
In this PR I am adding exports in package.json.
This request came through the task below:
[INT-247 - JS:  add exports fields in package.json](https://storyblok.atlassian.net/browse/INT-247)
To test, download the branch on your machine and run the commands:
```
npm run build 
npm run test
```
Any questions I'm available!
> refactor(int-247): JS: add exports fields in package.json

- package-lock.json
- package.json
Move `prettier` & `rollup-plugin-mjs-entry` to devDependencies so they won't be installed after distributed as a package
* Run `npm pack` to build this into a tarball, say `storyblok-js-client-4.5.2.tgz`
* Create a new project and init with `npm init -y`
* Install from tarball `npm i /path/to/storyblok-js-client-4.5.2.tgz`
* `prettier` and `rollup-plugin-mjs-entry` should no longer be in `package-lock.json` or `node_modules`
The `package-lock.json` seems to be out of sync with `package.json`
And the `yarn.lock` won't be affected by this change.
> chore(deps): move prettier & rollup-plugin-mjs-entry to devDependencies

- types/index.d.ts
Better typescript support
- Prior to this using the filterquery operation `is` results in a type error
- 
-
> add type for filter query operation `is`

- types/index.d.ts
The storyId of event types `change` and `published` it's a number, not a string (as you can see on the image below). This PR fixes that.
> fix: correct the storyId type to number

- src/interfaces.ts
- Added dimensions related features to ISbStoriesParams interface.
Jira Link: [INT-632](https://storyblok.atlassian.net/browse/INT-632)
One can test it doing an API call like:
`const { data } = client.get('cdn/datasource_entries', {
datasource: 'labels',
dimension: 'en',
cv,
});`
- Typescript shouldn't complain about trying to use datasource or dimension in the API call
> fix(INT-632): adding dimension interface

- src/sbFetch.ts
- tests/index.test.js
DON'T MERGE BEFORE THE QA APROVE
Jira Link: [INT-741](https://storyblok.atlassian.net/browse/INT-741)
You could create a js file and import the js-client, (This specific branch), and run the file bellow:
```js
const StoryblokClient = require('storyblok-js-client')
let sbApi = new StoryblokClient({
accessToken: 'LQUIllrMLaXARdVTG2Fp2Qtt',
// timeout: 1,
})
for (let index = 0; index < 30; index++) {
sbApi.get('cdn/links', {
version: 'draft',
})
.then((response) => {
console.log('Works! =>', index)
})
.catch((error) => {
console.log('Error =>', index, error)
})
}
```
- Now the abort function that aborted the requests only works if the user passes timeout in the settings
A error message from the script above
[INT-741]: https://storyblok.atlassian.net/browse/INT-741?atlOrigin=eyJpIjoiNWRkNTljNz …
> fix(int-741): Error when the user are fetching data from published links

- README.md
Chore. I have no Jira link since it's just a small thing reported by @johannes-lindgren to me
Please check the type of change your PR introduces:-->
Review the content of the readme file.
I updated the readme file as the `config` parameters. The `oauthToken` parameter was missing. The `cache` parameter is actually optional so I updated it. The `accessToken` and oauthToken` are optional but at leas one of them is required so I updated both to be optional with the note that the first is mandatory for the CDN API only and the second one for the MAPI only.
> chore: client config params updated in readme

- src/index.ts
- src/sbHelpers.ts
- tests/units/helpers.test.js
Jira Link: [INT-729](https://storyblok.atlassian.net/browse/INT-729)
To test in Chinese spaces you only need to pass the region code 'cn', like in the example bellow:
```js
const sbApi = new StoryblokClient({
accessToken: 'YOUR_ACCESS_TOKEN',
region: 'cn', // to China is 'cn', United States 'us' and to Europe 'eu'
version: "draft", // optional
})
sbApi.get(`cdn/stories`, { version: 'draft' })
.then(({ data }) => {
console.log(`Works in China =>`, data.stories)
})
.catch((error) => {
console.log('Error =>', error)
})
```
- Now it's possible to use the SDK with Chinese spaces 😄 
[INT-729]: https://storyblok.atlassian.net/browse/INT-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> task(int-729): adding support for china region

- src/richTextResolver.ts
- src/schema.ts
- tests/constants/richTextResolver.js
- tests/richTextResolver.test.js
Jira Link: [INT-822](https://storyblok.atlassian.net/browse/INT-822)
1. Download this branch
2. Build this branch and install in your file test bellow `yarn prepare`
3. run the code bellow, the results need to be the correct html for the new and old types
```js
import StoryblokClient from 'storyblok-js-client'
try {
const sbApi = new StoryblokClient({
accessToken: 'njqqM5pRfbBoBHZ2dYm4YAtt',
})
await sbApi.get(`cdn/stories/home`)
.then((response) => {
const story = response.data.story
const RT_DATA = story.content.ritch_text // The .rich_text is the name of your richtext field inside your story
console.log(sbApi.richTextResolver.render(RT_DATA)) // console the json parsed
})
.catch((error) => {
console.log('Error =>', error)
})
} catch (error) {
console.log('Error try =>', error)
}
``` …
> feat(int 822): Full Emoji support in richtext resolver

- src/index.ts
- src/interfaces.ts
- src/richTextResolver.ts
- src/schema.ts
- tests/constants/richTextResolver.js
- tests/richTextResolver.test.js
[The idea is to fix this issue](https://github.com/storyblok/storyblok-js-client/issues/543)
- Now if the color attributes are not passed correctly, the renderer will not create the span tags.
> fix(int-916): Fix problem with colors in richtext resolver

- package.json
- Fix
Jira Link: 
- React or Gatsby SDK side
i.e. Gatsby SDK: `lib/types.ts`, `ISbStoryData` didn't have the correct TS types detected. Suggestions from the text editor were not showing the available values.
1. Find node_modules, go to `@storyblok`
2. Add changes from [https://github.com/storyblok/storyblok-js-client/compare/main...fix/ts-types-export-config](https://github.com/storyblok/storyblok-js-client/compare/main...fix/ts-types-export-config)
3. TS types work correctly
- JS Client side
1. Fetch `fix/ts-types-export-config` branch
4. Pull changes
5. Build if necessary 
- TS type exports pointed to the correct files (See at the root [package.json](https://github.com/storyblok/storyblok-js-client/compare/main...fix/ts-types-export-config))
- TS type suggestions from the text editor …
> fix: add exports TS types files in root package.json

- README.md
- src/constants.ts
- src/index.ts
Jira Link: [INT-977](https://storyblok.atlassian.net/browse/INT-977)
Now is possible to pass custom headers, to identify the client and the request in our infrastructure
If no default headers it's not passed, the js-client will add a default header for that.
```js
const Storyblok = new StoryblokClient({
accessToken: 'NICE_TOKEN',
cache: { type: 'memory', clear: 'auto' },
headers: {
'SB-Agent': "SB-FE" // Default header for the V2 Frontend
'SB-Agent-Version': "2.0.0" // Default header for the V2 version
}
})
```
- It's possible to use custom headers, add in config object
- Now in all request the js-client send the default header to identify the client in the infrastructure.
[INT-977]: https://storyblok.atlassian.net/browse/INT-977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> feat(int-976): Adding default header

- src/interfaces.ts
Request a random story and log the result, compare what you get with what the typing says you should've gotten.
Example:
This fixes the typings that were broken in #697 and makes sure that the typing actually matches the API response.
All of these are on the `ISbStoryData` interface.
Many are fields have to be optional, as they are not always returned. I've marked them as optional as well, because [you specifically requested that from the last fix](https://github.com/storyblok/storyblok-js-client/pull/738#discussion_r1450562270), although the API does return `null` instead in many cases, so this will still be slightly incorrect typing.
One of the changes stands out, and that is marking `parent` as optional. Anything else is impossible over JSON, as a recursive structure needs an anchor; …
> fix: update typings to match api response

- src/index.ts
Run the build command, it should create the lib typedefs in `dist/types/index.d.ts` and the interface `ISbResponseData` should be exported.
Exporting types from the Storyblok CLI is triggering an error related to `ISbResponseData` not being exported by the `storyblok-js-client` package.
This PR exports the interface `ISbResponseData` so that it shouldn't trigger any error in such cases (tested with @alexjoverm)
> WEB-790 - Export ISbResponseData interface

- src/index.ts
This PR fixes the issue number 2 from #806. The issue is intermittent because of a combination of factors, but in some cases it will result in the JS Client serving cached content even after flushing the cache, because the `flushCache` method clears the cache but it doesn't clear the cached `cv` value used for performing requests.
In order to simulate a case that would be affected by this bug, you can run the following script. To get the accessToken, spaceId, storyId and get added to the space for testing, please DM me. Of course you can setup your own space and script, but with this one it will be quick :-) 
If you run it on the main branch, you will always get the same values for all the 3 requests. With this branch you will get the current value after flushing the cache.
```
import …
```
> fix: clear cacheVersions on flushCache

- src/index.ts
This PR fixes an issue with a potential loop of infinite retries in case the API returns a 429 response when rate limits are hit. It also updates the retry delay as the current one is too big, and it gets really big as the number of times increases, extending the execution time of the script in case of multiple 429 errors. 
Jira Link: [SHAPE-2460](https://storyblok.atlassian.net/browse/SHAPE-2460)
Test on the main branch:
- Add this `throw {status: 429, response: "err"}` to [this line](https://github.com/storyblok/storyblok-js-client/blob/b6abea25646e93016d1ee080aae3538f6751d7ab/src/index.ts#L642).
- Perform a get request with the client.
- Check the console. You should see an infinite loop of error messages.
Test on this branch:
- Add this `throw {status: 429, response: "err"}` on line …
> Fix(SHAPE-2460):retries loop bug

- .gitignore
- playground/main.ts
- src/index.ts
- src/richTextResolver.ts
Warning campaign
Run the playground
- When user imports the legacy `RichtextResolver` and uses `render` function, a warning should show on the console
> feat: pro 425 deprecation warnings legacy richtext

- src/richTextResolver.ts
- Add a property to `tag.attrs` prototype
- Render a Richtext field
- Check that the added property is NOT looped over
This PR fixes a potential security issue related to looping over object properties without assessing if they are object own properties or part of the prototype chain.
> Fix: check for ownProperties on Richtext renderer HTML attributes

- playground/vanilla/src/main.ts
- src/index.ts
Fixes https://github.com/storyblok/storyblok-cli/issues/107
- Run the vanilla playground
`headers` property now supports both object based headers or `new Headers` 
```ts
const headers = new Headers()
headers.append('Awiwi', 'Awiwi')
const headers2 = {
'Awiwi': 'Awiwi'
}
// Both should work
// 2. Initialize the client with the preview token
// from your space dashboard at https://app.storyblok.com
const Storyblok = new StoryblokClient({
accessToken: import.meta.env.VITE_ACCESS_TOKEN as string,
headers,
})
```
> fix: support object based headers

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Based on @ryami333 feedback on #842 
> The purpose of [matrix strategies](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#about-matrix-strategies) is "Running variations of jobs in a workflow". Configuring this job with a matrix strategy is redundant for two reasons:
> You've only put one element (20) in the matrix, so it's effectively the same as running it without a matrix strategy at all. You could have just written the Node version directly in the actions/setup-node step, as it was before this PR.
You wouldn't want to add any other versions to this particular workflow's matrix, because you wouldn't be able be publish the package two-or-more times. For "testing" / "linting" workflows it makes sense to run …
> chore: ci improvements

- src/index.ts
Please check the type of change your PR introduces:-->
With this change the cv cache is now flushed even with published versions so that the content is kept up to date. Fixes issue #823.
> feat: improve cv cache flushing

- src/index.test.ts
- src/index.ts
Closes #822 
Call `getAll()` with a slug with a trailing slash. Before this PR, this results in a TypeError.
No TypeError in the above mentioned case.
> fix: remove trailing slash from slug passed to getAll()

- .github/dependabot.yml
- .github/workflows/commitlint.yml
- .github/workflows/lint.yml
- .github/workflows/pkg.pr.new.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .husky/commit-msg
- .npmrc
- eslint.config.mjs
- package.json
- playground/vanilla/src/main.ts
- pnpm-lock.yaml
- src/constants.ts
- src/entry.esm.ts
- src/entry.umd.ts
- src/index.test.ts
- src/index.ts
- src/interfaces.ts
- src/richTextResolver.ts
- src/sbFetch.test.ts
- src/sbFetch.ts
- src/sbHelpers.test.ts
- src/sbHelpers.ts
- src/schema.ts
- src/throttlePromise.ts
- tests/api/index.e2e.ts
- vitest.config.ts
Package update, linting refactoring
Update the dependency in any running project: nothing should break.
Style changes.
> chore: update eslint, using our shared conf, and update every dev deps

- src/throttlePromise.ts
Hopefully solves some of the CLI issues with correct error handling on the throttle
> fix: properly reject throttle queue errors

- README.md
- src/index.ts
- src/sbFetch.test.ts
- src/sbFetch.ts
FIxes #884 
Call a delete operation without providing the second argument
The `StoryblokClient.delete()` method can be called without passing the second `params` argument.
> fix: params in delete method should be optional

- src/index.test.ts
- src/index.ts
Fix nested relations resolution in Storyblok SDK
Internal ref: #13985
1. Create a story with nested relations (e.g., an event_slider with spots containing event_type relations)
2. Request the story with resolve_relations including both direct and nested relations:
```typescript
const response = await Storyblok.get("cdn/stories/your-story", {
version: "draft",
resolve_relations: [
"event.event_type",
"event_slider.spots"
]
});
```
3. Verify that nested relations (like `story.content.body[0].spots[0].content.event_type`) are properly resolved to objects instead of remaining as UUIDs
- Fixed nested relations resolution by improving the field pattern matching in `_insertRelations`
- Added support for resolving relations at any nesting level within the content tree
- Added unit tests to verify …
> fix: resolve nested relations in content blocks properly

- .github/workflows/commitlint.yml
- .github/workflows/lint.yml
- .github/workflows/pkg.pr.new.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- package.json
- pnpm-lock.yaml
Update to dev dependencies, add simple-git-hooks
-
-
-
> Update dev deps, add simple-git-hooks

- src/index.test.ts
- src/index.ts
- src/interfaces.ts
Fixes: #909 
1. Install dependencies and run tests:
```bash
pnpm install
pnpm test
```
2. Try using the cdn/links endpoint with TypeScript:
```typescript
const { data } = await storyblokApi.get('cdn/links', {
version: 'draft',
include_dates: 1
});
// TypeScript should properly recognize all fields including dates
console.log(data.links['some-uuid'].created_at);
```
3. Verify that other endpoints still work as expected with their original types.
- Added proper typing for cdn/links endpoint parameters through ISbLinksParams interface
- Added ISbLinkWithDates interface to include date fields when include_dates is set
- Implemented function overloads for the get method to provide correct typing based on the endpoint
- Added comprehensive test suite covering various edge cases and scenarios
- …
> Add proper typing for cdn/links endpoint and include_dates parameter

- changelog.md
When a user of this library wants to learn what changed between releases, they might look at the `changelog.md` file. This gives them the wrong impression that the library is no longer describing it changes between releases because the changelog ends at a version from a year ago.
> chore: mark changelog.md as deprecated

- src/interfaces.ts
ISbContentMangmntAPI posts via `storyblok.post() accepts `sort_by_date` in the payload but it isn't included in the type definition
Jira Link: INT-random-guy-on-the-internet
- Added a single line to interfaces type file.
> add sort_by_date definition to ISbContentMangmntAPI type def

- src/index.test.ts
- src/sbHelpers.test.ts
- src/sbHelpers.ts
Fixes: #960 
A recent commit added the `starts_with` param to the recursive `resolve_relations` method, and when the param is undefined it produces a `starts_with=undefined` URL which breaks the API.
This commit fixes the bug by stripping null or undefined values from the final URL.
Unit tests included.
> fix: having null or undefined values breaks stringify

- package.json
- src/index.test.ts
- src/index.ts
- src/interfaces.ts
Call `get` or `getAll` trying to resolve more than 50 relations.
- Fixed relation resolution when handling more than 50 relations
- The client now correctly resolves all relations, regardless of the number
- Added a test that specifically checks resolving more than 50 relations
- When relations exceed 50, the client properly replaces `rel_uuids` with fully resolved objects
The Storyblok API returns `rel_uuids` instead of `rels` when there are more than 50 relations. The client was correctly fetching these relations in chunks but wasn't properly integrating them back into the response structure, causing the relation resolution to fail. This fix ensures that chunked relations are properly handled.
> fix: add all relations back to the response when resolving more than 50
