README.md
dist/index.js
package-lock.json
package.json
source/index.js

Hey. I have noticed that your client is not supporting proxy. So I forked your project and added a proxy support. Can you review it and merge? Because I need it this for my project.

Add proxy support for axios client

---

dist/index.d.ts

https://www.storyblok.com/cl/url-resolving

Align with API

---

dist/index.d.ts

Can't reference these interfaces without redefining them which is not ideal

Export interfaces from index.d.ts

---

dist/index.d.ts

Changes:
* add `getAll`definition type in index.d.ts file
Reference: #28

Add getAll typing in index.d.ts

---

package-lock.json
package.json
source/schema.js
tests/richTextResolver.test.js

This PR:
* Fixes the issue #37
* Update Jest to latest version, [v25.1](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2510)

Add mailto before email address

---

dist/index.d.ts

add missing type first_published_at to StoryData

add missing type first_published_at

---

package-lock.json
package.json
source/index.js
tests/index.test.js
types/index.d.ts

This PR fixes:
* #66 
* #61 
* #50

hotfixes and features to v3

---

types/index.d.ts

fix(types): add missing field to storyblok event payload

---

source/helpers.js
source/index.js
tests/units/helpers.test.js

feat(client): improve parallelism in get-all method

---

types/index.d.ts

fix: added `language` to `StoriesParams`

Add type definition

---

package-lock.json

fix(int-122): dependabots alerts

---

source/index.js

- Added verification to check keys from API.
Jira Link: [INT-393](https://storyblok.atlassian.net/browse/INT-393)
Just install, instantiate and test the SDK, either using an oAuth token or not to check if the SDK is working properly.
Bugs related to this task should be solved.
Any questions, please let me know.
Thanks @romeucarvalho for the insights here.

`INT-393` - fix(int-393): resolve links

---

src/index.ts

- Added the correct function return to get, getAll, set and flush functions
Jira Link: [INT-633](https://storyblok.atlassian.net/browse/INT-633)
- Added the correct returns to the following functions: get, getAll, set and flush

fix(INT-633): fixing function return

---

src/schema.ts
tests/constants/richTextResolver.js
tests/richTextResolver.test.js

Jira Link: [ft-459](url)
Adds support for color highlighting in the richtext resolver. You can run `yarn test richTextResolver` to run the new test cases added
-
-
-

feat(ft-459): richtext color

---

README.md
src/index.ts

Jira Link: [INT-852](https://storyblok.atlassian.net/browse/INT-852)
This PR solves the problem of resolving nested relations. With the code below, run it pointing to production and note that the generated json has 426 lines, and only first-level relations will be resolved.
After generating the json download the js-client in this branch and point the test script to use this branch, you will notice that now the file will have more than a thousand lines and all relations will be resolved.
Change the name of the `jsClientVersion` variable when running the second time, to have two diff files.
The script below generates a json with the return
This change is exactly the same as V4, you can see here => https://github.com/storyblok/storyblok-js-client/blob/v4/source/index.js#L69
```js
import …
```

fix(int-852): change default state of the resolve nested relations

---

README.md

Jira Link: [INT-926](https://storyblok.atlassian.net/browse/INT-926)
Read the readme 😄 
- Update cache docs
- Remove the proxy section of the readme
[INT-926]: https://storyblok.atlassian.net/browse/INT-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

task(int-926): Update docs for cache and proxy

---

src/interfaces.ts
src/sbHelpers.ts
src/schema.ts
tests/richTextResolver.test.js

feat: Adding ampersand escape for the links href

---

src/interfaces.ts

Jira Link: [INT-1029](https://storyblok.atlassian.net/browse/INT-1029)
Import the interface and check f everithing it's ok
- Now the `ISbAlternateObject` has all attributes like the api
[INT-1029]: https://storyblok.atlassian.net/browse/INT-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

task(int-1029): Update `ISbAlternateObject` interface

---

.github/workflows/release.yml

Adding `release.yml` file

---

src/sbFetch.ts

Jira Link: [INT-1212](https://storyblok.atlassian.net/browse/INT-1212)
Try to pass parameters and use the custom fetch function.
Need to be tested in node and front end environments.
[INT-1212]: https://storyblok.atlassian.net/browse/INT-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(int-1212): Fix issue with fetch fn not using provided in params

---

src/interfaces.ts

fix(types): added asset mapi params interface

---

.github/workflows/release.yml
package.json

Introduces automatic releases on pre-release channels (next, beta)

chore(ci): enable automatic next release

---

playground/vanilla/src/main.ts
src/richTextResolver.ts

- Just added a new parameter to the method with the deprecation to avoid duplicates and be able to suppress the warning from the SDKs

fix: add option to supress deprecation warning

---

.github/workflows/pkg.pr.new.yml

chore: add pkg.pr.new

---

README.md

docs: adjust links to point to new API Docs

---

src/index.test.ts
src/interfaces.ts

Closes PR #862 
Fetch a Story and verify all fields are covered by the interface.

fix: add missing fields to Story object

---

.github/workflows/pkg.pr.new.yml

ci: force latest corepack

---

.github/workflows/commitlint.yml
.github/workflows/pkg.pr.new.yml
package.json
pnpm-lock.yaml
vite.config.ts

chore: update dev deps, skip some jobs if author is dependabot

---

.github/workflows/license-checker.yml
package.json
pnpm-lock.yaml
scripts/license-checker.mjs

Introduces a new license checking mechanism:
- Added a GitHub workflow to check project dependencies' licenses
- Created a license-checker script to validate allowed licenses
- Updated package.json with a new script for running license checks
-
-
-

chore: add license checker workflow and script

---

playground/vanilla/package.json
playground/vanilla/src/main.ts
playground/vanilla/vite.config.ts
pnpm-lock.yaml
src/index.ts
src/interfaces.ts

This PR introduce an opt-in feature flag to inline assets metadata when using `resolve_assets`

feat: 985-inline-assets-as-opt-in
